server:
  port: 8008
#? ??? ?? ?? ??? ????? ??? ??
spring:
  security: #???? ??? ??? ?? ????
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul    #mySQL?????? ??
    username: root               # MySQL ??? ?? ??
    password: 1234	    # MySQL ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver  # ??????? DB? ??? ? ?? ?? ????

  jpa:  # DB? ?? ?? ?? ???? ??
    open-in-view: false          # JPA ??? ? ????? ???? ?? (N+1 ??)
    hibernate:
      ddl-auto: update  # ???? ???? ???? ?? ??? ??????(??? ????/????)
    show-sql: true       #??? SQL? ???? ?? ??? ???? ??
    properties:
      hibernate:
        format_sql: true # ?? SQL ???? ??? ?? ?? ? ???? ????.

  servlet:
    multipart:
      max-file-size: 100MB #?? ??? 1?? ?? 100MB
      max-request-size: 200MB # ?? ??(?? ?? ? ??) ?? ??


  thymeleaf:
    cache: false #?? ? ??? ?? ????
logging:
  level:
    org.hibernate.SQL: debug #?? ??? ????? ??? ? ???? ??
    org.hibernate.orm.jdbc.bind: trace  # ???? ????(?)?? ??
